name: 'Deploy prod'


on:
  push:
    tags:
      - v**

jobs:
  upload-prod-mage:
    runs-on: ubuntu-latest
    name: Upload docker prod image
    env:
      IMAGE_TAG: ${{ github.run_number }}
    outputs:
      image_tag: ${{ env.GITHUB_REF_NAME }}
    steps: 
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and upload image
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64 
          tags: | 
            ${{ steps.login-ecr.outputs.registry }}/go-tiny-prod:${{ env.IMAGE_TAG }}
            ${{ steps.login-ecr.outputs.registry }}/go-tiny-prod:latest
          push: true
