name: 'Deploy dev'


on:
  push:
    branches:
      - master

jobs:
  upload-dev-mage:
    runs-on: ubuntu-latest
    name: Upload docker dev image
    env:
      IMAGE_TAG: ${{ github.run_number }}
    outputs:
      image_tag: ${{ env.IMAGE_TAG }}
    steps: 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and upload image
        uses: docker/build-push-action@v3
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/arm64 
          tags: | 
            ${{ steps.login-ecr.outputs.registry }}/go-tyny-dev:${{ env.IMAGE_TAG }}
            ${{ steps.login-ecr.outputs.registry }}/go-tiny-dev:latest
          push: true
